// AppData.jsx — Toutes les données mock de la plateforme Maintenant!
// Exportées globalement via window.AppData

const AppData = {

  // ── PÉTITIONS ─────────────────────────────────────────────
  petitions: [
    { id: 1, title: "Stop à la fermeture des urgences de nuit à l'Hôpital Saint-Antoine", category: "Santé", signatures: 14820, goal: 20000, location: "Paris", author: "Collectif Urgences 75", date: "2026-03-10", featured: true, status: "active", description: "Depuis le 1er mars, les urgences de nuit de Saint-Antoine ferment à minuit. Des dizaines de patients sont refoulés chaque semaine. Nous exigeons le rétablissement immédiat du service 24h/24.", tags: ["santé publique", "hôpital", "Paris"], image: null },
    { id: 2, title: "Pour une loi de transition écologique ambitieuse avant 2027", category: "Écologie", signatures: 38400, goal: 50000, location: "France", author: "Alliance Verte", date: "2026-02-15", featured: true, status: "active", description: "La France doit se doter d'une loi contraignante pour atteindre la neutralité carbone. Nous réclamons une réforme fiscale verte, la fin des subventions aux énergies fossiles et un plan de rénovation énergétique massif.", tags: ["climat", "écologie", "loi"], image: null },
    { id: 3, title: "Augmentation du SMIC à 1 800 € net — maintenant !", category: "Social", signatures: 92300, goal: 100000, location: "France", author: "Syndicat CGT", date: "2026-01-20", featured: true, status: "active", description: "Avec l'inflation, le SMIC ne couvre plus les besoins essentiels. Nous demandons une revalorisation immédiate à 1 800 € net, indexée sur le coût de la vie.", tags: ["salaires", "travail", "inégalités"], image: null },
    { id: 4, title: "Non à la privatisation de la RATP", category: "Transport", signatures: 27600, goal: 40000, location: "Île-de-France", author: "Usagers des Transports", date: "2026-03-25", featured: false, status: "active", description: "La privatisation de la RATP menace l'accès aux transports pour tous. Les exemples étrangers montrent une dégradation du service et une hausse des tarifs. Non à la marchandisation du bien commun !", tags: ["transport", "service public", "privatisation"], image: null },
    { id: 5, title: "Logement social pour tous — fin des expulsions locatives en hiver", category: "Logement", signatures: 19200, goal: 25000, location: "France", author: "DAL — Droit au Logement", date: "2026-02-28", featured: false, status: "active", description: "Chaque année, des milliers de familles sont expulsées pendant l'hiver malgré la trêve hivernale. Nous exigeons un moratoire permanent sur les expulsions et un plan d'urgence logement social.", tags: ["logement", "expulsion", "solidarité"], image: null },
    { id: 6, title: "Pour la gratuité des transports en commun pour les moins de 26 ans", category: "Transport", signatures: 45100, goal: 60000, location: "France", author: "Union Étudiante", date: "2026-01-05", featured: false, status: "active", description: "La mobilité est un droit. Les jeunes doivent pouvoir se déplacer librement pour étudier, travailler, s'engager. La gratuité des transports pour les moins de 26 ans est une urgence sociale.", tags: ["jeunesse", "mobilité", "éducation"], image: null },
    { id: 7, title: "Justice pour les victimes de violences policières", category: "Justice", signatures: 61800, goal: 80000, location: "France", author: "Collectif Justice et Vérité", date: "2026-03-01", featured: false, status: "active", description: "Les violences policières ne sont pas des faits isolés mais un problème systémique. Nous demandons une commission d'enquête indépendante et des poursuites effectives contre les agents responsables.", tags: ["police", "violences", "droits humains"], image: null },
    { id: 8, title: "Réforme du droit à l'avortement : IVG dans la Constitution", category: "Droits", signatures: 103400, goal: 120000, location: "France", author: "Collectif Féministe National", date: "2025-11-12", featured: false, status: "active", description: "Le droit à l'IVG est constamment menacé. Son inscription dans la Constitution est une victoire, mais son accès réel dans tous les territoires doit être garanti par des financements et des structures adaptées.", tags: ["féminisme", "droits", "santé"], image: null },
    { id: 9, title: "Stop aux méga-bassines — l'eau est un bien commun", category: "Écologie", signatures: 34700, goal: 50000, location: "Poitou-Charentes", author: "Soulèvements de la Terre", date: "2026-02-10", featured: false, status: "active", description: "Les méga-bassines détournent l'eau des rivières et des nappes phréatiques au profit de l'agro-industrie intensive. L'eau appartient à tous — nous exigeons l'arrêt des chantiers.", tags: ["eau", "agriculture", "nature"], image: null },
    { id: 10, title: "Pour un revenu universel de base à 900 € dès 18 ans", category: "Économie", signatures: 78200, goal: 100000, location: "France", author: "Mouvement pour le RUB", date: "2026-01-15", featured: false, status: "active", description: "Un revenu universel de base permettrait à chacun de vivre dignement, de se former, de créer, de s'engager. Expérimenté dans plusieurs pays, il réduit la pauvreté sans décourager le travail.", tags: ["revenu", "solidarité", "économie"], image: null },
    { id: 11, title: "Référendum d'initiative citoyenne en toutes matières (RIC)", category: "Démocratie", signatures: 56400, goal: 80000, location: "France", author: "Collectif RIC France", date: "2026-03-05", featured: false, status: "active", description: "Le RIC permet aux citoyen·nes de proposer, abroger ou modifier des lois sans passer par les seul·es élu·es. Outil démocratique majeur pour redonner la voix au peuple.", tags: ["démocratie", "RIC", "souveraineté"], image: null },
    { id: 12, title: "Reconnaissance de la fraude fiscale comme crime contre la société", category: "Économie", signatures: 42100, goal: 60000, location: "France", author: "Attac France", date: "2026-02-20", featured: false, status: "active", description: "100 milliards d'euros par an échappent à l'impôt en France. Nous demandons l'inscription de la fraude fiscale grave parmi les crimes les plus sévèrement punis, avec confiscation des biens.", tags: ["fiscalité", "justice", "égalité"], image: null },
    { id: 13, title: "Création d'un fonds national de solidarité face aux catastrophes climatiques", category: "Solidarité", signatures: 23800, goal: 40000, location: "France", author: "Croix-Rouge française", date: "2026-04-01", featured: false, status: "active", description: "Inondations, canicules, incendies : les sinistré·es ne peuvent plus attendre des mois pour être indemnisé·es. Création d'un fonds abondé par les pollueurs, distribué en moins de 30 jours.", tags: ["climat", "solidarité", "indemnisation"], image: null },
  ],

  // ── MOBILISATIONS ─────────────────────────────────────────
  mobilizations: [
    { id: 1, title: "Grande Marche Nationale pour le Climat", date: "2026-05-10", time: "14:00", location: "Paris — Place de la République", type: "Manifestation", participants: 8400, description: "Rejoignez la plus grande mobilisation climatique de l'année. Marche pacifique de la République à Nation.", organizer: "Alliance Verte + XR France", image: null },
    { id: 2, title: "Assemblée Populaire contre les Privatisations", date: "2026-05-17", time: "15:00", location: "Lyon — Place Bellecour", type: "Assemblée", participants: 1200, description: "Forum citoyen ouvert à tous pour discuter des alternatives à la privatisation des services publics.", organizer: "Collectif Services Publics", image: null },
    { id: 3, title: "Grève Nationale des Services Publics", date: "2026-05-22", time: "09:00", location: "France entière", type: "Grève", participants: 45000, description: "Journée nationale de grève à l'appel de la CGT, FO, FSU et Solidaires. Rassemblements dans toutes les grandes villes.", organizer: "Intersyndicale", image: null },
    { id: 4, title: "Nuit Debout Écologique", date: "2026-06-01", time: "20:00", location: "Bordeaux — Place de la Victoire", type: "Veillée", participants: 650, description: "Nuit de débat, musique militante et projections sur l'urgence climatique. Buffet solidaire et ateliers.", organizer: "Collectif Bordeaux en Lutte", image: null },
    { id: 5, title: "Rassemblement pour le Droit au Logement", date: "2026-06-08", time: "11:00", location: "Marseille — Vieux-Port", type: "Rassemblement", participants: 3200, description: "En réponse à la crise du logement qui frappe Marseille, venez demander un plan d'urgence au préfet.", organizer: "DAL Marseille + ATD Quart Monde", image: null },
    { id: 6, title: "Festival Politique de la Résistance", date: "2026-06-14", time: "10:00", location: "Toulouse — Prairie des Filtres", type: "Festival", participants: 12000, description: "3 jours de conférences, concerts, débats et ateliers. Intervenants : syndicalistes, philosophes, artistes engagés.", organizer: "THE99COINPROJECT", image: null },
    { id: 7, title: "Marche des Fiertés Militante", date: "2026-06-21", time: "14:00", location: "Nantes — Place du Commerce", type: "Manifestation", participants: 5600, description: "La Marche des Fiertés de Nantes intègre cette année un bloc militant contre les LGBTphobies institutionnelles.", organizer: "Collectif LGBT+ Nantes", image: null },
    { id: 8, title: "Forum Social Européen — Volet France", date: "2026-07-03", time: "09:00", location: "Strasbourg — Palais des Congrès", type: "Forum", participants: 2800, description: "Rencontre internationale de militants, ONG et syndicats pour construire une Europe sociale et écologique.", organizer: "FSE France", image: null },
    { id: 9, title: "Blocage Non-Violent d'une Raffinerie", date: "2026-07-12", time: "06:00", location: "Le Havre", type: "Action directe", participants: 900, description: "Action de désobéissance civile non-violente contre la raffinerie de Normandie. Formation aux techniques de blocage pacifique.", organizer: "Extinction Rebellion Normandie", image: null },
    { id: 10, title: "Camp de Résistance Écologique", date: "2026-08-01", time: "00:00", location: "Larzac — Millau", type: "Camp", participants: 7800, description: "3 semaines de camp militant : ateliers, formations, actions terrain. Le Larzac, symbole de la lutte paysanne, vous accueille.", organizer: "Conf' Paysanne + Attac", image: null },
  ],

  // ── LOGEMENT ──────────────────────────────────────────────
  housing: [
    { id: 1, title: "Studio lumineux — coeur de Lyon Croix-Rousse", price_t99cp: 24, type: "Studio", rooms: 1, area: 28, location: "Lyon 4e", host: "Camille B.", rating: 4.9, reviews: 23, available: "Dès maintenant", description: "Beau studio rénové, lumineux, dans le quartier militant de la Croix-Rousse. Toutes commodités, proche tramway.", amenities: ["WiFi", "Cuisine équipée", "Chauffage"], image: null, solidarity: true },
    { id: 2, title: "Chambre chez l'habitant — famille solidaire, Paris 20e", price_t99cp: 18, type: "Chambre", rooms: 1, area: 14, location: "Paris 20e", host: "Marc & Julie", rating: 5.0, reviews: 8, available: "Immédiat", description: "Chambre dans appartement familial. Partage des repas possible. Accueil chaleureux pour personnes en difficulté.", amenities: ["WiFi", "Repas partagés", "Jardin"], image: null, solidarity: true },
    { id: 3, title: "T3 spacieux pour famille — Grenoble quartier Europole", price_t99cp: 38, type: "T3", rooms: 3, area: 72, location: "Grenoble", host: "Sonia T.", rating: 4.7, reviews: 15, available: "15 mai", description: "Grand appartement familial, idéal pour relogement temporaire suite sinistre ou mutation. 3 mois minimum.", amenities: ["WiFi", "Parking", "Cave", "Balcon"], image: null, solidarity: false },
    { id: 4, title: "Maison à la campagne — Ardèche, nature et calme", price_t99cp: 35, type: "Maison", rooms: 4, area: 110, location: "Ardèche", host: "Pierre L.", rating: 4.8, reviews: 31, available: "Dès maintenant", description: "Maison en pierre rénovée avec jardin de 800m². Idéale pour se ressourcer, télétravailler, ou pour familles.", amenities: ["Jardin", "Terrasse", "Cheminée", "Animaux acceptés"], image: null, solidarity: false },
    { id: 5, title: "Chambre militante — colocation engagée, Toulouse", price_t99cp: 16, type: "Chambre", rooms: 1, area: 12, location: "Toulouse", host: "Collectif Habitat Solidaire", rating: 4.6, reviews: 19, available: "1er juin", description: "Chambre dans colocation de 4 personnes très engagées. Cuisine solidaire, partage de ressources, ateliers hebdo.", amenities: ["WiFi", "Vélos", "Potager collectif"], image: null, solidarity: true },
    { id: 6, title: "Appartement T2 — Nantes centre, court séjour", price_t99cp: 28, type: "T2", rooms: 2, area: 45, location: "Nantes", host: "Amandine G.", rating: 4.5, reviews: 42, available: "Disponible", description: "Appartement moderne en plein centre-ville. Idéal pour militants en déplacement, accès toutes lignes.", amenities: ["WiFi haut débit", "Lave-linge", "Cuisine complète"], image: null, solidarity: false },
    { id: 7, title: "Loft artistique — Montreuil, grande terrasse", price_t99cp: 45, type: "Loft", rooms: 2, area: 85, location: "Montreuil (93)", host: "Atelier du Peuple", rating: 4.9, reviews: 12, available: "Dès maintenant", description: "Loft d'artiste avec grande terrasse, quartier militant de Montreuil. Parfait pour résidences artistiques ou colloques.", amenities: ["Terrasse 30m²", "Grand atelier", "Sono disponible"], image: null, solidarity: true },
    { id: 8, title: "Studio étudiant solidaire — Rennes Beaulieu", price_t99cp: 14, type: "Studio", rooms: 1, area: 20, location: "Rennes", host: "UNEF Rennes", rating: 4.4, reviews: 7, available: "Septembre 2026", description: "Studio disponible pour étudiant boursier en difficulté. Loyer en T99CP symbolique. Priorité aux étudiants engagés.", amenities: ["WiFi", "Bibliothèque partagée"], image: null, solidarity: true },
    { id: 9, title: "Gîte coopératif — Bretagne, bord de mer", price_t99cp: 42, type: "Gîte", rooms: 5, area: 130, location: "Finistère", host: "Coopérative Ker Armorik", rating: 4.8, reviews: 28, available: "Été 2026", description: "Gîte géré en coopérative. 5 chambres, salle commune, accès plage. Séjours militants et familiaux bienvenus.", amenities: ["Vue mer", "Jardin potager", "Salle de réunion", "Vélos"], image: null, solidarity: true },
    { id: 10, title: "Appartement T4 en co-hébergement — Strasbourg", price_t99cp: 22, type: "T4", rooms: 4, area: 95, location: "Strasbourg", host: "Réseau Solidarités Alsace", rating: 4.7, reviews: 11, available: "Immédiat", description: "Grand T4 proposé en co-hébergement solidaire pour personnes en transition (sortie de rue, réfugiés, femmes victimes de violence).", amenities: ["WiFi", "Transports à 5min", "Accompagnement social"], image: null, solidarity: true },
  ],

  // ── COVOITURAGE ───────────────────────────────────────────
  carpooling_offers: [
    { id: 1, from: "Paris — Gare de Lyon", to: "Lyon — Part-Dieu", date: "2026-05-15", time: "07:30", seats: 3, price_t99cp: 8, driver: "Thomas R.", rating: 4.9, car: "Renault Zoé (électrique)", note: "Silencieux, pas de musique forte, arrêt possible Mâcon.", comfort: ["Climatisation", "Chargeur USB"] },
    { id: 2, from: "Bordeaux", to: "Toulouse", date: "2026-05-16", time: "09:00", seats: 2, price_t99cp: 5, driver: "Amina K.", rating: 4.8, car: "Citroën C3", note: "Militante écolo, discussion politique bienvenue 😄", comfort: ["Musique folk", "Pause café"] },
    { id: 3, from: "Marseille", to: "Nice", date: "2026-05-17", time: "08:00", seats: 4, price_t99cp: 6, driver: "Jean-Paul M.", rating: 4.7, car: "Peugeot 308", note: "Départ ponctuel. Arrêt Toulon possible.", comfort: ["Climatisation", "Bagages acceptés"] },
    { id: 4, from: "Nantes", to: "Rennes", date: "2026-05-18", time: "17:30", seats: 2, price_t99cp: 3, driver: "Sophie D.", rating: 5.0, car: "Volkswagen ID.3 (électrique)", note: "Retour covoiturage après manif Nantes.", comfort: ["Chargeur rapide", "Confort premium"] },
    { id: 5, from: "Strasbourg", to: "Paris", date: "2026-05-20", time: "06:00", seats: 3, price_t99cp: 10, driver: "Lucas H.", rating: 4.6, car: "Skoda Octavia", note: "Longue route, ambiance détendue, arrêts prévus.", comfort: ["Grands coffres", "Pause repas"] },
    { id: 6, from: "Grenoble", to: "Lyon", date: "2026-05-21", time: "07:00", seats: 3, price_t99cp: 4, driver: "Fatima Z.", rating: 4.9, car: "Toyota Yaris", note: "Trajet quotidien, fiable et ponctuelle.", comfort: ["Calme", "Musique douce"] },
    { id: 7, from: "Lille", to: "Paris", date: "2026-05-22", time: "07:00", seats: 4, price_t99cp: 7, driver: "Omar B.", rating: 4.8, car: "Seat Leon", note: "Trajet pour la grève nationale — camarades bienvenus !", comfort: ["Climatisation", "USB"] },
    { id: 8, from: "Paris", to: "Bordeaux", date: "2026-05-24", time: "14:00", seats: 2, price_t99cp: 9, driver: "Céline P.", rating: 4.7, car: "Tesla Model 3", note: "Voiture 100% électrique. Super confort.", comfort: ["Autopilot autoroute", "Musique premium"] },
    { id: 9, from: "Montpellier", to: "Marseille", date: "2026-05-25", time: "10:00", seats: 3, price_t99cp: 4, driver: "Rachid A.", rating: 4.5, car: "Renault Clio", note: "Départ flexible ±30min. Ambiance sympa.", comfort: ["Climatisation"] },
    { id: 10, from: "Toulouse", to: "Bordeaux", date: "2026-05-28", time: "16:00", seats: 2, price_t99cp: 5, driver: "Manon T.", rating: 4.9, car: "Nissan Leaf (électrique)", note: "Retour festival. Discussion politique welcome !", comfort: ["Silence", "Vue panoramique"] },
  ],

  carpooling_requests: [
    { id: 1, from: "Paris", to: "Lyon", date: "2026-05-15", time: "Flexible matin", passenger: "Marie L.", note: "Pour rejoindre l'assemblée populaire. Participerai aux frais en T99CP." },
    { id: 2, from: "Lyon", to: "Grenoble", date: "2026-05-17", time: "08:00", passenger: "Kevin B.", note: "Étudiant, peu de moyens. Mobilisation pour le logement." },
    { id: 3, from: "Bordeaux", to: "Paris", date: "2026-05-20", time: "Flexible", passenger: "Nadia R.", note: "Urgence familiale. Cherche conducteur de confiance." },
    { id: 4, from: "Marseille", to: "Montpellier", date: "2026-05-16", time: "Matin", passenger: "Antoine G.", note: "Pour forum social. Budget limité." },
    { id: 5, from: "Rennes", to: "Nantes", date: "2026-05-18", time: "17:00", passenger: "Lola M.", note: "Retour après réunion syndicale." },
    { id: 6, from: "Toulouse", to: "Montpellier", date: "2026-05-22", time: "Flexible", passenger: "Ibrahim D.", note: "Trajet pour stage militant. Participera aux frais." },
    { id: 7, from: "Strasbourg", to: "Colmar", date: "2026-05-19", time: "18:00", passenger: "Claire F.", note: "Retour réunion politique. 1 valise." },
    { id: 8, from: "Nice", to: "Marseille", date: "2026-05-23", time: "Matin", passenger: "Paul N.", note: "Rendez-vous médical, pas de voiture." },
    { id: 9, from: "Paris", to: "Lille", date: "2026-05-25", time: "09:00", passenger: "Sara H.", note: "Conférence féministe à Lille. Budget étudiant." },
    { id: 10, from: "Lyon", to: "Clermont-Ferrand", date: "2026-05-28", time: "Flexible", passenger: "Baptiste C.", note: "Rencontre coopérative paysanne. Sympathique compagnie assurée !" },
  ],

  // ── KI PRÊTE TOUT ─────────────────────────────────────────
  lending: [
    { id: 1, name: "Appareil à raclette 8 personnes", category: "Cuisine", owner: "Pierre V.", location: "Paris 11e", price_t99cp: 3, deposit_t99cp: 15, available: true, condition: "Excellent", description: "Raclette Tefal pour 8 personnes, complète avec spatules. Parfait pour soirées solidaires !", image: null },
    { id: 2, name: "Livre : L'Empire ne peut plus rien contre nous — Michael Parenti", category: "Livres", owner: "Fatima K.", location: "Lyon", price_t99cp: 0, deposit_t99cp: 5, available: true, condition: "Bon", description: "Essai politique incontournable. Rendu dans les 3 semaines svp.", image: null },
    { id: 3, name: "Perceuse-visseuse Bosch 18V + accessoires", category: "Bricolage", owner: "Marc D.", location: "Bordeaux", price_t99cp: 4, deposit_t99cp: 20, available: true, condition: "Très bon", description: "Perceuse sans fil avec 2 batteries et coffret d'accessoires complet. Idéale pour petits travaux.", image: null },
    { id: 4, name: "Broyeur de végétaux électrique", category: "Jardin", owner: "Sylvie M.", location: "Nantes", price_t99cp: 6, deposit_t99cp: 30, available: false, condition: "Bon", description: "Broyeur 2400W pour branches jusqu'à 40mm. Parfait pour le compost !", image: null },
    { id: 5, name: "Service à fondue complète 8 personnes", category: "Cuisine", owner: "Jean-Luc B.", location: "Grenoble", price_t99cp: 2, deposit_t99cp: 10, available: true, condition: "Excellent", description: "Service à fondue en fonte avec rechaud à alcool, 8 fourchettes. Idéal pour soirées d'hiver.", image: null },
    { id: 6, name: "Jeu Les Aventuriers du Rail Europe", category: "Jeux", owner: "Céline R.", location: "Toulouse", price_t99cp: 2, deposit_t99cp: 20, available: true, condition: "Très bon", description: "Version Europe complète, toutes les pièces présentes. Pour 2 à 5 joueurs.", image: null },
    { id: 7, name: "Kärcher haute pression K4", category: "Bricolage", owner: "Ahmed T.", location: "Marseille", price_t99cp: 8, deposit_t99cp: 40, available: true, condition: "Bon", description: "Nettoyeur haute pression avec lance, tuyau 6m. Parfait pour terrasses, voitures, vélos.", image: null },
    { id: 8, name: "Enceinte Bluetooth Marshall Stanmore", category: "Audio", owner: "Lucie P.", location: "Montpellier", price_t99cp: 5, deposit_t99cp: 25, available: true, condition: "Excellent", description: "Enceinte Marshall haut de gamme. Son exceptionnel. Pour soirées, ateliers, événements.", image: null },
    { id: 9, name: "Piano électronique Yamaha 61 touches + stand", category: "Musique", owner: "Oscar N.", location: "Strasbourg", price_t99cp: 8, deposit_t99cp: 50, available: false, condition: "Très bon", description: "Piano numérique 61 touches avec stand réglable, pédale sustain et alimentation. Idéal pour cours ou pratique.", image: null },
    { id: 10, name: "Tente de camping 4 personnes Quechua", category: "Plein air", owner: "Rosa L.", location: "Rennes", price_t99cp: 5, deposit_t99cp: 20, available: true, condition: "Bon", description: "Tente 4 places montage facile 2 minutes. Idéale pour camps militants, festivals et vacances solidaires.", image: null },
  ],

  // ── MARKETPLACE ───────────────────────────────────────────
  marketplace: [
    { id: 1, title: "Vélo de ville femme — Excellent état", category: "Sport & Vélo", price_t99cp: 55, condition: "Excellent", location: "Paris", seller: "Ingrid B.", description: "Vélo femme 7 vitesses, panier avant, antivol inclus. Peu utilisé, très bon état.", image: null },
    { id: 2, title: "Smartphone Samsung Galaxy S21 — débloqué", category: "High-Tech", price_t99cp: 120, condition: "Très bon", location: "Lyon", seller: "Karim Z.", description: "Galaxy S21 avec chargeur et housse. Batterie 95%. Débloqué tout opérateur.", image: null },
    { id: 3, title: "Lot de livres politiques (15 ouvrages)", category: "Livres", price_t99cp: 18, condition: "Bon", location: "Paris", seller: "Martine D.", description: "Bourdieu, Foucault, Rancière, Eribon, Lordon... Lot de 15 essais en très bon état.", image: null },
    { id: 4, title: "Table de cuisine ronde IKEA — blanche", category: "Mobilier", price_t99cp: 22, condition: "Bon", location: "Bordeaux", seller: "Léa F.", description: "Table ronde IKEA LISABO, diamètre 105cm. Quelques légères rayures. Démontée, à récupérer.", image: null },
    { id: 5, title: "Baskets Nike Air Force 1 — taille 42, bon état", category: "Vêtements", price_t99cp: 7, condition: "Bon", location: "Toulouse", seller: "Tom B.", description: "Air Force 1 blanches portées une saison, propres, semelles en bon état.", image: null },
    { id: 6, title: "Planche de surf longboard 9'0", category: "Sport & Vélo", price_t99cp: 95, condition: "Très bon", location: "Biarritz", seller: "Pedro A.", description: "Longboard 9 pieds, shape classique, 3 ailerons, leash inclus. Quelques craquelures mineures.", image: null },
    { id: 7, title: "Machine à coudre Singer — électrique", category: "Maison", price_t99cp: 38, condition: "Très bon", location: "Nantes", seller: "Christine P.", description: "Singer électrique 23 points. Manette à vitesse variable. Notice et accessoires inclus.", image: null },
    { id: 8, title: "Canapé convertible 3 places — tissu gris", category: "Mobilier", price_t99cp: 75, condition: "Bon", location: "Marseille", seller: "Yasmine K.", description: "Canapé-lit 3 places convertible, couchage 140×190. À transporter soi-même.", image: null },
    { id: 9, title: "Manteau laine femme Sandro — taille 38", category: "Vêtements", price_t99cp: 30, condition: "Excellent", location: "Paris", seller: "Alice R.", description: "Manteau Sandro 100% laine, couleur camel, porté 2 fois. Taille 38 (S/M).", image: null },
    { id: 10, title: "Guitare acoustique Yamaha F310 + étui", category: "Musique", price_t99cp: 42, condition: "Bon", location: "Grenoble", seller: "Nathan M.", description: "Guitare acoustique 6 cordes avec étui rigide. Légèrement griffée, sons parfaits.", image: null },
    { id: 11, title: "Appareil photo reflex Canon 750D + objectif", category: "High-Tech", price_t99cp: 155, condition: "Très bon", location: "Strasbourg", seller: "Élodie V.", description: "Canon 750D boîtier + 18-55mm f/3.5-5.6. ~20k déclenchements. Chargeur et 2 batteries inclus.", image: null },
    { id: 12, title: "Chaussures de randonnée Salomon — taille 44", category: "Sport & Vélo", price_t99cp: 20, condition: "Bon", location: "Grenoble", seller: "Paul C.", description: "Salomon XA Pro 3D, taille 44, 2 sorties seulement. Gore-Tex imperméable.", image: null },
    { id: 13, title: "Cocotte-minute SEB 10L — inox", category: "Maison", price_t99cp: 18, condition: "Très bon", location: "Rennes", seller: "Brigitte T.", description: "SEB Autocuiseur inox 10L. Toutes plaques dont induction. Complète avec panier.", image: null },
    { id: 14, title: "Tapis persan fait main 2×3m", category: "Maison", price_t99cp: 85, condition: "Bon", location: "Lyon", seller: "Farida N.", description: "Tapis persan authentique 200×300cm. Motifs floraux, couleurs chaudes. Belle pièce.", image: null },
    { id: 15, title: "Kit jardinage complet — 8 outils", category: "Jardin", price_t99cp: 14, condition: "Bon", location: "Nantes", seller: "Michel B.", description: "8 outils (bêche, râteau, fourche, binette...) en acier forgé avec manches bois.", image: null },
    { id: 16, title: "Imprimante laser HP — couleur", category: "High-Tech", price_t99cp: 28, condition: "Bon", location: "Paris", seller: "Vincent L.", description: "HP Color LaserJet Pro. Cartouches à 40%. Idéale pour militants et associations.", image: null },
    { id: 17, title: "Veste en jean vintage — taille M", category: "Vêtements", price_t99cp: 8, condition: "Bon", location: "Toulouse", seller: "Zoé A.", description: "Veste en jean vintage années 90, customisée avec patches politiques. Originale !", image: null },
    { id: 18, title: "Mixeur professionnel Vitamix", category: "Cuisine", price_t99cp: 90, condition: "Très bon", location: "Paris", seller: "Emma S.", description: "Vitamix Explorian, utilisé 6 mois. Puissance 1400W, bol 2L. Pour cuisines collectives.", image: null },
    { id: 19, title: "Vélo cargo électrique Bakfiets", category: "Sport & Vélo", price_t99cp: 280, condition: "Bon", location: "Bordeaux", seller: "Rémi G.", description: "Cargo électrique hollandais pour enfants ou livraisons. Batterie 400Wh, 80km d'autonomie.", image: null },
    { id: 20, title: "Dictionnaire encyclopédique 3 volumes (1980)", category: "Livres", price_t99cp: 4, condition: "Bon", location: "Grenoble", seller: "Henri D.", description: "Grand Larousse 3 volumes, excellent état pour l'âge. Culture générale complète.", image: null },
  ],

  // ── MEDIA ─────────────────────────────────────────────────
  media: [
    { id: 1, title: "Comment les milliardaires ont capturé la démocratie française", category: "Enquête", author: "Sandrine Moreau", date: "2026-04-18", reading_time: 12, premium: false, excerpt: "En dix ans, la fortune des 100 plus riches Français a triplé tandis que les services publics s'effondraient. Une enquête exclusive sur les mécanismes de capture du pouvoir politique par l'oligarchie.", tags: ["démocratie", "inégalités", "oligarchie"], image: null, featured: true },
    { id: 2, title: "Réforme des retraites : ce que les médias mainstream n'ont pas dit", category: "Politique", author: "Julien Carpentier", date: "2026-04-15", reading_time: 8, premium: false, excerpt: "Derrière les chiffres de l'exécutif, une réalité sociale bien différente. Analyse des projections officielles et de leurs contradictions.", tags: ["retraites", "social", "mensonge"], image: null, featured: true },
    { id: 3, title: "Urgence climatique : les promesses brisées d'un gouvernement aux abonnés absents", category: "Écologie", author: "Clara Lefèvre", date: "2026-04-12", reading_time: 10, premium: false, excerpt: "Chaque rapport du GIEC est suivi d'annonces spectaculaires et d'une inaction structurelle. Décryptage du greenwashing gouvernemental.", tags: ["climat", "gouvernement", "GIEC"], image: null, featured: false },
    { id: 4, title: "Violences policières : le déni institutionnel a un coût", category: "Justice", author: "Moussa Diallo", date: "2026-04-10", reading_time: 15, premium: false, excerpt: "Analyse des 847 cas documentés depuis 2020. Qui sont les victimes ? Quels recours ? Pourquoi les poursuites restent rares ?", tags: ["police", "justice", "droits"], image: null, featured: false },
    { id: 5, title: "La grande illusion du marché carbone européen", category: "Économie", author: "Brigitte Aumont", date: "2026-04-08", reading_time: 9, premium: false, excerpt: "Le marché carbone européen (ETS) devait réduire les émissions. Les données montrent qu'il a surtout enrichi les pollueurs.", tags: ["carbone", "Europe", "économie verte"], image: null, featured: false },
    { id: 6, title: "Portrait : Kadi Touré, syndicaliste et visage d'une jeunesse en lutte", category: "Portrait", author: "Amina Bensalem", date: "2026-04-05", reading_time: 7, premium: false, excerpt: "À 24 ans, Kadi Touré est déléguée syndicale dans un entrepôt Amazon de la banlieue lyonnaise. Rencontre avec une militante de terrain.", tags: ["syndicat", "jeunesse", "travail"], image: null, featured: false },
    { id: 7, title: "Eau, semences, forêts : l'accaparement silencieux des communs naturels", category: "Écologie", author: "Nicolas Farges", date: "2026-04-02", reading_time: 11, premium: false, excerpt: "Des fonds d'investissement rachètent des aquifères en Andalousie, des forêts en Amazonie, des terres agricoles en Afrique. Un pillage planétaire documenté.", tags: ["eau", "accaparement", "communs"], image: null, featured: false },
    { id: 8, title: "Blockchain militante : T99CP, une monnaie au service du peuple", category: "Innovation", author: "Omar Benzara", date: "2026-03-28", reading_time: 6, premium: false, excerpt: "Présentation du projet THE99COINPROJECT : une cryptomonnaie sur Polygon dont la valeur est indexée sur le temps de travail humain.", tags: ["crypto", "T99CP", "solidarité"], image: null, featured: false },
    { id: 9, title: "Logement : pourquoi la France construit-elle des bureaux plutôt que des HLM ?", category: "Logement", author: "Patricia Renault", date: "2026-03-25", reading_time: 8, premium: false, excerpt: "En 10 ans, 40% de moins de logements sociaux construits alors que la demande explose. Les raisons politiques et financières de ce choix.", tags: ["HLM", "logement social", "crise"], image: null, featured: false },
    { id: 10, title: "Entretien avec Hartmut Rosa : 'L'accélération sociale est une forme de violence'", category: "Culture", author: "Sophie Leclercq", date: "2026-03-20", reading_time: 13, premium: false, excerpt: "Le sociologue allemand revient sur sa théorie de la résonance et les alternatives possibles au capitalisme de l'urgence.", tags: ["philosophie", "société", "aliénation"], image: null, featured: false },
  ],

  // ── JARDIN / SURPLUS ──────────────────────────────────────
  garden: [
    { id: 1, item: "Surplus de tomates cerises — 2kg", giver: "Marguerite P.", location: "Toulouse", quantity: "2 kg", free: true, type: "Légume", description: "Tomates cerises du jardin, trop pour moi seule ! À venir chercher ce week-end.", image: null },
    { id: 2, item: "Plants de framboisiers (12 plants)", giver: "Robert L.", location: "Alsace", quantity: "12 plants", free: true, type: "Plant", description: "Divisions de framboisiers remontants. À récupérer en pot, idéals pour potager.", image: null },
    { id: 3, item: "Cerises — environ 5 kg", giver: "Élisabeth M.", location: "Drôme", quantity: "5 kg", free: true, type: "Fruit", description: "Cerisier productif cette année. Cerises douces, à consommer rapidement. Panier à apporter.", image: null },
    { id: 4, item: "Courges butternut — 8 pièces", giver: "David G.", location: "Lot-et-Garonne", quantity: "8 courges", free: true, type: "Légume", description: "Magnifiques butternut de mon potager bio. Se conservent 3 mois à l'abri.", image: null },
    { id: 5, item: "Compost mûr — sac de 25L", giver: "Collectif Jardin Partagé", location: "Paris 19e", quantity: "25 litres", free: true, type: "Autre", description: "Compost 100% naturel issu de notre jardin partagé. Excellent pour potagers et jardinières.", image: null },
    { id: 6, item: "Œufs de poules élevées en plein air — 30 pièces", giver: "Ferme Solidaire des Cévennes", location: "Gard", quantity: "30 œufs", free: false, price_t99cp: 3, type: "Œufs", description: "Poules en plein air, alimentation sans OGM. Œufs très frais du jour de livraison.", image: null },
    { id: 7, item: "Bouquet de menthe fraîche", giver: "Sylviane T.", location: "Lyon", quantity: "Grand bouquet", free: true, type: "Herbe", description: "Menthe envahissante ! Prenez-en autant que vous voulez. Idéale pour tisanes et mojitos.", image: null },
    { id: 8, item: "Sirop de mélisse fait maison — 50cl", giver: "Hélène B.", location: "Bretagne", quantity: "1 bouteille", free: false, price_t99cp: 4, type: "Autre", description: "Sirop artisanal de mélisse fraîche cueillie dans mon jardin. Recette familiale, sans conservateur.", image: null },
    { id: 9, item: "Miel de lavande de Provence — 500g", giver: "Apiculteur Bio Var", location: "Var", quantity: "500g pot", free: false, price_t99cp: 8, type: "Autre", description: "Miel de lavande récolte 2026. Ruches non traitées, miellée certifiée. Goût exceptionnel.", image: null },
    { id: 10, item: "Abricots frais — caissette 3kg", giver: "Pierre-Yves A.", location: "Ardèche", quantity: "3 kg", free: false, price_t99cp: 4, type: "Fruit", description: "Abricots du verger, variété Bergeron, récoltés à maturité. À consommer en 3 jours.", image: null },
    { id: 11, item: "Courgettes rondes et longues — lot de 10", giver: "Nicolas F.", location: "Gironde", quantity: "10 courgettes", free: true, type: "Légume", description: "Grosse production cette année ! Courgettes vertes et rondes, parfaites pour farcir.", image: null },
    { id: 12, item: "Noisettes fraîches — sac de 2kg", giver: "Suzanne V.", location: "Périgord", quantity: "2 kg", free: false, price_t99cp: 3, type: "Fruit", description: "Noisettes récoltées à la main en forêt. À sécher ou à consommer fraîches. Délicieuses !", image: null },
  ],

  // ── SEL — SYSTÈME D'ÉCHANGE LOCAL ─────────────────────────
  sel: [
    { id: 1, service: "Cours de yoga — débutants et intermédiaires", provider: "Aisha R.", location: "Paris 10e", duration_min: 60, category: "Bien-être", description: "Yoga Vinyasa adapté à tous niveaux. Cours collectifs de 5 pers. max. À domicile ou parc.", available: "Week-end", image: null },
    { id: 2, service: "Cours d'anglais — conversationnel", provider: "James H.", location: "Lyon", duration_min: 60, category: "Formation", description: "Natif britannique, prof certifié. Accent sur la conversation quotidienne et professionnelle.", available: "Soirs en semaine", image: null },
    { id: 3, service: "Plomberie — petites réparations", provider: "Claude M.", location: "Marseille", duration_min: 60, category: "Artisanat", description: "Plombier retraité. Robinets, WC, joint, fuite... Je dépanne avec plaisir les personnes isolées.", available: "Sur RDV", image: null },
    { id: 4, service: "Jardinage et conseil potager", provider: "Lucie V.", location: "Toulouse", duration_min: 60, category: "Jardin", description: "Maraîchère bio de formation. Aide à l'installation d'un potager, taille, entretien.", available: "Samedi matin", image: null },
    { id: 5, service: "Initiation au tango argentin", provider: "Carlos & Marta B.", location: "Bordeaux", duration_min: 90, category: "Culture", description: "Couple de danseurs professionnels. Cours pour débutants, ambiance conviviale, 2 à 4 personnes.", available: "Vendredi soir", image: null },
    { id: 6, service: "Cours de maths — lycée / prépa", provider: "Benjamin A.", location: "Grenoble", duration_min: 60, category: "Formation", description: "Normalien, prof de maths. Soutien lycée, classes prépa, rattrapage examens.", available: "Mercredi & week-end", image: null },
    { id: 7, service: "Garde d'enfants (babysitting)", provider: "Camille D.", location: "Nantes", duration_min: 60, category: "Famille", description: "Auxiliaire de puériculture diplômée. Enfants de 0 à 10 ans. Références disponibles.", available: "Soirs et week-end", image: null },
    { id: 8, service: "Ménage et repassage solidaire", provider: "Fatou S.", location: "Paris 18e", duration_min: 60, category: "Maison", description: "Aide à domicile expérimentée. En priorité pour personnes âgées, malades ou en difficulté.", available: "Lundi–Vendredi", image: null },
    { id: 9, service: "Réparation vélo — toutes marques", provider: "Thomas R.", location: "Strasbourg", duration_min: 60, category: "Artisanat", description: "Mécanicien vélo passionné. Entretien, révision, réparation ponctuelle. Conseils gratuits.", available: "Sur RDV", image: null },
    { id: 10, service: "Aide informatique — seniors bienvenue", provider: "Marie-Claire P.", location: "Nice", duration_min: 60, category: "Informatique", description: "Informaticienne retraitée. Initiation à l'ordinateur, smartphone, internet, applications.", available: "Matin en semaine", image: null },
    { id: 11, service: "Traduction français–arabe–anglais", provider: "Karim Z.", location: "Lille", duration_min: 60, category: "Formation", description: "Traducteur assermenté trilingue. Documents officiels, correspondances, démarches administratives.", available: "Flexible", image: null },
    { id: 12, service: "Couture et retouches vêtements", provider: "Élodie N.", location: "Rennes", duration_min: 60, category: "Artisanat", description: "Couturière professionnelle. Ourlet, zip, transformation, upcycling vêtements.", available: "Week-end", image: null },
    { id: 13, service: "Soutien scolaire — primaire CE1/CE2/CM", provider: "Julie T.", location: "Montpellier", duration_min: 60, category: "Formation", description: "Institutrice certifiée, 10 ans d'expérience. Lecture, écriture, calcul. Enfants de 7 à 10 ans.", available: "Mercredi & week-end", image: null },
    { id: 14, service: "Photo reportage événement militant", provider: "Oscar L.", location: "Paris", duration_min: 120, category: "Culture", description: "Photographe engagé. Couverture de manifestations, assemblées, événements. Fichiers HD fournis.", available: "Sur RDV", image: null },
    { id: 15, service: "Aide à la rédaction — lettres, CV, démarches", provider: "Nathalie B.", location: "Lyon", duration_min: 60, category: "Formation", description: "Rédactrice professionnelle. Aide à la rédaction de CVs, lettres de motivation, recours administratifs.", available: "Sur RDV", image: null },
    { id: 16, service: "Massage bien-être — technique suédoise", provider: "Laure V.", location: "Bordeaux", duration_min: 60, category: "Bien-être", description: "Masseuse diplômée. Massage suédois de détente. Huiles naturelles biologiques. Confidentialité assurée.", available: "Semaine et week-end", image: null },
    { id: 17, service: "Comptabilité pour associations et petites structures", provider: "Patrick M.", location: "Nantes", duration_min: 60, category: "Informatique", description: "Expert-comptable retraité. Bénévole pour associations, auto-entrepreneurs et petites coopératives.", available: "Sur RDV", image: null },
    { id: 18, service: "Cours de guitare — acoustique et électrique", provider: "Romain C.", location: "Toulouse", duration_min: 60, category: "Culture", description: "Musicien professionnel, 15 ans d'enseignement. Débutants à avancés. Rock, folk, blues.", available: "Soirs", image: null },
    { id: 19, service: "Aide à la recherche de logement solidaire", provider: "Réseau DAL Île-de-France", location: "Paris", duration_min: 90, category: "Social", description: "Accompagnement pour personnes en difficulté de logement : dossiers, recours, contacts associations.", available: "Permanences jeudi", image: null },
    { id: 20, service: "Médiation et gestion de conflits", provider: "Dr. Isabelle R.", location: "Strasbourg", duration_min: 90, category: "Social", description: "Médiatrice certifiée, 20 ans d'expérience. Conflits de voisinage, familiaux, collectifs de travail.", available: "Sur RDV", image: null },
  ],

  // ── CROWDFUNDING ──────────────────────────────────────────
  crowdfunding: [
    { id: 1, title: "Caisse de grève — cheminots SNCF Île-de-France", category: "Luttes", raised_t99cp: 3840, goal_t99cp: 8000, contributors: 142, days_left: 18, description: "Soutien aux cheminots grévistes pendant les négociations salariales. Chaque contribution compte !", organizer: "CGT Cheminots IDF", featured: true },
    { id: 2, title: "Financement du camp de résistance écologique du Larzac", category: "Solidaires", raised_t99cp: 6200, goal_t99cp: 10000, contributors: 287, days_left: 42, description: "Pour accueillir 8 000 militants cet été, nous avons besoin de financer les infrastructures, la cuisine solidaire et les animations.", organizer: "THE99COINPROJECT", featured: true },
    { id: 3, title: "Recours juridique contre l'expulsion de la ZAD des Hauts", category: "Luttes", raised_t99cp: 2100, goal_t99cp: 5000, contributors: 93, days_left: 12, description: "Financement des honoraires d'avocats pour bloquer l'expulsion de la zone à défendre des Hauts-de-France.", organizer: "Collectif ZAD Nord", featured: false },
    { id: 4, title: "Soutien à la paysannerie bio — coopérative Terre Commune", category: "Solidaires", raised_t99cp: 4500, goal_t99cp: 12000, contributors: 201, days_left: 56, description: "Aide à l'installation de 5 maraîchers bio en AMAP. Financement du matériel et de la première saison.", organizer: "Conf' Paysanne Sud-Ouest", featured: false },
  ],

  // ── PROFIL UTILISATEUR PAR DÉFAUT ─────────────────────────
  // ── SONDAGES ──────────────────────────────────────────────
  polls: [
    {
      id: 1, slug: 'presidentielle-2027-1er-tour',
      type: 'electoral',
      category: 'Élection présidentielle',
      title: 'Présidentielle 2027 — Si le 1er tour avait lieu dimanche prochain ?',
      desc: "Pour qui voteriez-vous au premier tour de l'élection présidentielle de 2027 ? Sondage sans valeur scientifique, réservé aux membres certifié·es de la plateforme.",
      author: 'Rédaction Maintenant!',
      created: '2026-04-12', closes: '2026-05-12',
      votes_total: 8421,
      requires_account: true,
      multi: false,
      options: [
        { id: 1, label: 'Lucie Castets',           party: 'Nouveau Front Populaire', color: '#DC2626', img: { emoji: '👩🏻‍🦱', photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop' }, votes: 2134 },
        { id: 2, label: 'François Ruffin',         party: 'Indépendant gauche',     color: '#7C3AED', img: { emoji: '👨🏻‍🦰', photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop' }, votes: 1987 },
        { id: 3, label: 'Marine Tondelier',        party: 'Les Écologistes',         color: '#16A34A', img: { emoji: '👩🏼', photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop' }, votes: 1456 },
        { id: 4, label: 'Édouard Philippe',        party: 'Horizons',                color: '#2563EB', img: { emoji: '👨🏻‍🦲', photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop' }, votes: 1320 },
        { id: 5, label: 'Jordan Bardella',         party: 'Rassemblement National',  color: '#1F2937', img: { emoji: '👨🏻', photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop' }, votes: 980 },
        { id: 6, label: 'Aucun des candidat·es',   party: 'Vote blanc',              color: '#6B7280', img: { emoji: '⚪', photo: 'https://images.unsplash.com/photo-1606326608690-4e0281b1e588?w=200&h=200&fit=crop' },  votes: 544 },
      ],
    },
    {
      id: 2, slug: 'retraites-64-ans',
      type: 'societe',
      category: 'Société',
      title: 'Faut-il abroger la réforme des retraites à 64 ans ?',
      desc: "La réforme adoptée en 2023 a porté l'âge légal de départ à 64 ans. Trois ans après, les conséquences sociales se font sentir. Quel est votre avis ?",
      author: 'Collectif Retraites',
      created: '2026-04-08', closes: '2026-06-01',
      votes_total: 14503,
      requires_account: true,
      multi: false,
      options: [
        { id: 1, label: "Oui, retour à 60 ans",                  desc: "Abrogation totale", color: '#DC2626', img: { emoji: '✊', photo: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=200&h=200&fit=crop' }, votes: 9214 },
        { id: 2, label: "Oui, retour à 62 ans",                  desc: "Abrogation partielle", color: '#E11D74', img: { emoji: '👍', photo: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=200&h=200&fit=crop' }, votes: 3210 },
        { id: 3, label: "Non, maintenir à 64 ans",                desc: "Statu quo", color: '#6B7280', img: { emoji: '⚖️', photo: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=200&h=200&fit=crop' }, votes: 1654 },
        { id: 4, label: "Plus tard, 67 ans",                       desc: "Aller plus loin", color: '#1F2937', img: { emoji: '👎', photo: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=200&h=200&fit=crop' }, votes: 425 },
      ],
    },
    {
      id: 3, slug: 'salaire-minimum-1800',
      type: 'societe',
      category: 'Économie & Social',
      title: 'Êtes-vous favorable à un SMIC à 1 800 € net ?',
      desc: "Plusieurs organisations syndicales et politiques proposent une augmentation du SMIC à 1 800 € net mensuels. Position de la communauté Maintenant!",
      author: 'Confédération syndicale 99%',
      created: '2026-04-15', closes: '2026-05-30',
      votes_total: 6240,
      requires_account: true,
      multi: false,
      options: [
        { id: 1, label: "Oui, immédiatement",                       desc: "Décret dès 2026",     color: '#16A34A', img: { emoji: '💰', photo: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=200&h=200&fit=crop' }, votes: 3890 },
        { id: 2, label: "Oui, progressivement sur 3 ans",            desc: "Étalement",          color: '#7C3AED', img: { emoji: '📈', photo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=200&h=200&fit=crop' }, votes: 1812 },
        { id: 3, label: "Non, augmentation moindre (~1 600 €)",      desc: "Compromis",          color: '#F59E0B', img: { emoji: '⚖️', photo: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=200&h=200&fit=crop' }, votes: 432 },
        { id: 4, label: "Non, le SMIC est suffisant",                 desc: "Maintien actuel",    color: '#6B7280', img: { emoji: '🚫', photo: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=200&h=200&fit=crop' }, votes: 106 },
      ],
    },
    {
      id: 4, slug: 'pronostic-municipales-paris-2026',
      type: 'pronostic',
      category: 'Pronostic électoral',
      title: 'Municipales Paris 2026 — Qui sera élu·e maire ?',
      desc: "Pronostic communautaire pour les municipales parisiennes de mars 2026. Qui pensez-vous succédera à la mairie ? (Pronostic uniquement — différent d'une intention de vote.)",
      author: 'Cellule Paris',
      created: '2026-04-10', closes: '2026-03-15',
      votes_total: 3210,
      requires_account: true,
      multi: false,
      options: [
        { id: 1, label: 'Rachida Dati',             party: 'Les Républicains',  color: '#1E40AF', img: { emoji: '👩🏻', photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&h=200&fit=crop' }, votes: 1120 },
        { id: 2, label: 'David Belliard',           party: 'Les Écologistes',    color: '#16A34A', img: { emoji: '👨🏻‍🦱', photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop' }, votes: 894 },
        { id: 3, label: 'Ian Brossat',              party: 'PCF / NFP',          color: '#DC2626', img: { emoji: '👨🏼', photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop' }, votes: 712 },
        { id: 4, label: 'Anne Hidalgo (suppléant·e)', party: 'PS',                 color: '#F472B6', img: { emoji: '👩🏼', photo: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop' }, votes: 380 },
        { id: 5, label: 'Autre',                     party: '—',                   color: '#6B7280', img: { emoji: '❓', photo: 'https://images.unsplash.com/photo-1606326608690-4e0281b1e588?w=200&h=200&fit=crop' }, votes: 104 },
      ],
    },
    {
      id: 5, slug: 'priorite-budget-participatif',
      type: 'societe',
      category: 'Budget participatif',
      title: 'Quelle priorité pour le budget participatif Maintenant! 2026 ?',
      desc: "La plateforme dispose de 18 500 T99CP à allouer cette année. Aidez-nous à choisir la priorité collective. Vote multiple : sélectionnez jusqu'à 3 options.",
      author: 'Conseil d\'administration',
      created: '2026-04-20', closes: '2026-05-05',
      votes_total: 1842,
      requires_account: true,
      multi: true, max_choices: 3,
      options: [
        { id: 1, label: 'Caisse de grève', desc: 'Soutien aux travailleur·ses en lutte',          color: '#DC2626', img: { emoji: '✊', photo: 'https://images.unsplash.com/photo-1591189863430-ab87e120f312?w=200&h=200&fit=crop' },  votes: 1320 },
        { id: 2, label: 'Hébergement militant', desc: 'Logement temporaire pour militant·es',      color: '#0891B2', img: { emoji: '🏠', photo: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=200&h=200&fit=crop' }, votes: 980 },
        { id: 3, label: 'Médias indépendants', desc: 'Soutenir le journalisme militant',           color: '#7C3AED', img: { emoji: '📰', photo: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=200&h=200&fit=crop' }, votes: 870 },
        { id: 4, label: 'Formation politique', desc: 'Universités populaires, ateliers',           color: '#F59E0B', img: { emoji: '🎓', photo: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=200&h=200&fit=crop' }, votes: 540 },
        { id: 5, label: 'Solidarité internationale', desc: 'Palestine, Sahel, etc.',                color: '#16A34A', img: { emoji: '🌍', photo: 'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?w=200&h=200&fit=crop' }, votes: 720 },
        { id: 6, label: 'Aide juridique', desc: 'Avocats militants, defense des manifestant·es',    color: '#1F2937', img: { emoji: '⚖️', photo: 'https://images.unsplash.com/photo-1589994965851-a8f479c573a9?w=200&h=200&fit=crop' }, votes: 410 },
      ],
    },
  ],

  defaultUser: {
    id: 1, name: "Marie Dupont", email: "marie@maintenant.org", avatar: null,
    t99cp_balance: 247, joined: "2025-06-12", location: "Paris",
    is_admin: false, badges: ["Signataire ×10", "Militant actif", "Contributeur SEL"],
    petitions_signed: 8, petitions_created: 2, services_used: 5,
    bio: "Militante écologiste et féministe. Engagée dans mon quartier depuis 10 ans.",
  },
};

window.AppData = AppData;
